global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "course-platform-monitor"

scrape_configs:
  - job_name: "course-platform-gateway"
    static_configs:
      - targets: ["gateway:3000"]
        labels:
          service: "gateway"
          environment: "development"
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "course-platform-monolith"
    static_configs:
      - targets: ["monolith:3000"]
        labels:
          service: "monolith"
          environment: "development"
    metrics_path: "/metrics"
    scrape_interval: 5s

  # - job_name: "course-platform-template"
  #   static_configs:
  #     - targets: ["template:3000"]
  #       labels:
  #         service: "template"
  #         environment: "development"
  #   metrics_path: "/metrics"
  #   scrape_interval: 5s
